baseURL = "https://surajyadav.xyz/"
languageCode = "en-us"
title = "Suraj Yadav"

[permalinks]
posts = "/posts/:title/"
fragments = "/fragments/:title/"
diary = "/diary"

[params]
diary = "diary"
fragments = "fragments"

[params.customCSS]
custom = "css/custom.css"