baseURL = "https://surajyadav.xyz/"
languageCode = "en-us"
title = "Suraj Yadav"
theme = "hugo-theme-mini"

[permalinks]
posts = "/posts/:title/"
fragments = "/fragments/:title/"
diary = "/diary"

[params]
diary = "diary"
fragments = "fragments"