baseURL = "https://surajyadav.xyz/"
languageCode = "en-us"
title = "Suraj Yadav"

[permalinks]
posts = "/posts/:title/"
diary = "/diary"

[params]
diary = "diary"
awesome = "awesome"

[Social]
github = "https://github.com/jarusll"