name: github pages

on:
  workflow_dispatch:
  repository_dispatch: # build on submodules push
    types: [diary_push, posts_push, fragments_push]
  push:
    branches:    
      - master 

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) 
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod 

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2 
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
